// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trbtvpsjjjjeegrkvojk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyYnR2cHNqampqZWVncmt2b2prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY5NjIwNDUsImV4cCI6MjA5MjUzODA0NX0.PFvvWXOmhImnf2duZnXXwbPtonYsPxJlrAukp9droOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});